import { d as defineEventHandler } from '../../nitro/nitro.mjs';
import 'node:http';
import 'node:https';
import 'node:events';
import 'node:buffer';
import 'node:fs';
import 'node:path';
import 'node:crypto';
import 'minimark/hast';
import 'node:url';
import '@iconify/utils';
import 'consola';
import 'better-sqlite3';
import 'ipx';

const github = defineEventHandler(() => {
  const peter3hg = {
    login: "PeterH3G",
    id: 500234,
    node_id: "MDQ6VXNlcjUwMDIzNA==",
    avatar_url: "https://avatars.githubusercontent.com/u/500234?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/PeterH3G",
    html_url: "https://github.com/PeterH3G",
    followers_url: "https://api.github.com/users/PeterH3G/followers",
    following_url: "https://api.github.com/users/PeterH3G/following{/other_user}",
    gists_url: "https://api.github.com/users/PeterH3G/gists{/gist_id}",
    starred_url: "https://api.github.com/users/PeterH3G/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/PeterH3G/subscriptions",
    organizations_url: "https://api.github.com/users/PeterH3G/orgs",
    repos_url: "https://api.github.com/users/PeterH3G/repos",
    events_url: "https://api.github.com/users/PeterH3G/events{/privacy}",
    received_events_url: "https://api.github.com/users/PeterH3G/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false,
    name: "PeterH3G",
    company: "PeterH3G",
    blog: "https://peterh3g.github.io",
    location: "Zwolle, The Netherlands",
    email: null,
    hireable: true,
    bio: "Always Be Coding",
    twitter_username: null,
    public_repos: 2,
    public_gists: 0,
    followers: 8,
    following: 13,
    created_at: "2010-11-28T15:11:05Z",
    updated_at: "2025-11-03T00:59:52Z"
  };
  const repositories = [
    {
      id: 355204775,
      node_id: "MDEwOlJlcG9zaXRvcnkzNTUyMDQ3NzU=",
      name: "peterh3g",
      full_name: "PeterH3G/peterh3g",
      private: false,
      owner: {
        login: "PeterH3G",
        id: 500234,
        node_id: "MDQ6VXNlcjUwMDIzNA==",
        avatar_url: "https://avatars.githubusercontent.com/u/500234?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/PeterH3G",
        html_url: "https://github.com/PeterH3G",
        followers_url: "https://api.github.com/users/PeterH3G/followers",
        following_url: "https://api.github.com/users/PeterH3G/following{/other_user}",
        gists_url: "https://api.github.com/users/PeterH3G/gists{/gist_id}",
        starred_url: "https://api.github.com/users/PeterH3G/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/PeterH3G/subscriptions",
        organizations_url: "https://api.github.com/users/PeterH3G/orgs",
        repos_url: "https://api.github.com/users/PeterH3G/repos",
        events_url: "https://api.github.com/users/PeterH3G/events{/privacy}",
        received_events_url: "https://api.github.com/users/PeterH3G/received_events",
        type: "User",
        user_view_type: "public",
        site_admin: false
      },
      html_url: "https://github.com/PeterH3G/peterh3g",
      description: "My Github README.md",
      fork: false,
      url: "https://api.github.com/repos/PeterH3G/peterh3g",
      forks_url: "https://api.github.com/repos/PeterH3G/peterh3g/forks",
      keys_url: "https://api.github.com/repos/PeterH3G/peterh3g/keys{/key_id}",
      collaborators_url: "https://api.github.com/repos/PeterH3G/peterh3g/collaborators{/collaborator}",
      teams_url: "https://api.github.com/repos/PeterH3G/peterh3g/teams",
      hooks_url: "https://api.github.com/repos/PeterH3G/peterh3g/hooks",
      issue_events_url: "https://api.github.com/repos/PeterH3G/peterh3g/issues/events{/number}",
      events_url: "https://api.github.com/repos/PeterH3G/peterh3g/events",
      assignees_url: "https://api.github.com/repos/PeterH3G/peterh3g/assignees{/user}",
      branches_url: "https://api.github.com/repos/PeterH3G/peterh3g/branches{/branch}",
      tags_url: "https://api.github.com/repos/PeterH3G/peterh3g/tags",
      blobs_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs{/sha}",
      git_tags_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/tags{/sha}",
      git_refs_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/refs{/sha}",
      trees_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/trees{/sha}",
      statuses_url: "https://api.github.com/repos/PeterH3G/peterh3g/statuses/{sha}",
      languages_url: "https://api.github.com/repos/PeterH3G/peterh3g/languages",
      stargazers_url: "https://api.github.com/repos/PeterH3G/peterh3g/stargazers",
      contributors_url: "https://api.github.com/repos/PeterH3G/peterh3g/contributors",
      subscribers_url: "https://api.github.com/repos/PeterH3G/peterh3g/subscribers",
      subscription_url: "https://api.github.com/repos/PeterH3G/peterh3g/subscription",
      commits_url: "https://api.github.com/repos/PeterH3G/peterh3g/commits{/sha}",
      git_commits_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/commits{/sha}",
      comments_url: "https://api.github.com/repos/PeterH3G/peterh3g/comments{/number}",
      issue_comment_url: "https://api.github.com/repos/PeterH3G/peterh3g/issues/comments{/number}",
      contents_url: "https://api.github.com/repos/PeterH3G/peterh3g/contents/{+path}",
      compare_url: "https://api.github.com/repos/PeterH3G/peterh3g/compare/{base}...{head}",
      merges_url: "https://api.github.com/repos/PeterH3G/peterh3g/merges",
      archive_url: "https://api.github.com/repos/PeterH3G/peterh3g/{archive_format}{/ref}",
      downloads_url: "https://api.github.com/repos/PeterH3G/peterh3g/downloads",
      issues_url: "https://api.github.com/repos/PeterH3G/peterh3g/issues{/number}",
      pulls_url: "https://api.github.com/repos/PeterH3G/peterh3g/pulls{/number}",
      milestones_url: "https://api.github.com/repos/PeterH3G/peterh3g/milestones{/number}",
      notifications_url: "https://api.github.com/repos/PeterH3G/peterh3g/notifications{?since,all,participating}",
      labels_url: "https://api.github.com/repos/PeterH3G/peterh3g/labels{/name}",
      releases_url: "https://api.github.com/repos/PeterH3G/peterh3g/releases{/id}",
      deployments_url: "https://api.github.com/repos/PeterH3G/peterh3g/deployments",
      created_at: "2021-04-06T13:47:05Z",
      updated_at: "2025-11-08T19:05:33Z",
      pushed_at: "2025-11-08T19:05:29Z",
      git_url: "git://github.com/PeterH3G/peterh3g.git",
      ssh_url: "git@github.com:PeterH3G/peterh3g.git",
      clone_url: "https://github.com/PeterH3G/peterh3g.git",
      svn_url: "https://github.com/PeterH3G/peterh3g",
      homepage: "",
      size: 222,
      stargazers_count: 2,
      watchers_count: 2,
      language: null,
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
        key: "mit",
        name: "MIT License",
        spdx_id: "MIT",
        url: "https://api.github.com/licenses/mit",
        node_id: "MDc6TGljZW5zZTEz"
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [],
      visibility: "public",
      forks: 0,
      open_issues: 0,
      watchers: 2,
      default_branch: "main"
    },
    {
      id: 984130434,
      node_id: "R_kgDOOqijgg",
      name: "peterh3g.github.io",
      full_name: "PeterH3G/peterh3g.github.io",
      private: false,
      owner: {
        login: "PeterH3G",
        id: 500234,
        node_id: "MDQ6VXNlcjUwMDIzNA==",
        avatar_url: "https://avatars.githubusercontent.com/u/500234?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/PeterH3G",
        html_url: "https://github.com/PeterH3G",
        followers_url: "https://api.github.com/users/PeterH3G/followers",
        following_url: "https://api.github.com/users/PeterH3G/following{/other_user}",
        gists_url: "https://api.github.com/users/PeterH3G/gists{/gist_id}",
        starred_url: "https://api.github.com/users/PeterH3G/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/PeterH3G/subscriptions",
        organizations_url: "https://api.github.com/users/PeterH3G/orgs",
        repos_url: "https://api.github.com/users/PeterH3G/repos",
        events_url: "https://api.github.com/users/PeterH3G/events{/privacy}",
        received_events_url: "https://api.github.com/users/PeterH3G/received_events",
        type: "User",
        user_view_type: "public",
        site_admin: false
      },
      html_url: "https://github.com/PeterH3G/peterh3g.github.io",
      description: "My Github Pages",
      fork: false,
      url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io",
      forks_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/forks",
      keys_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/keys{/key_id}",
      collaborators_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/collaborators{/collaborator}",
      teams_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/teams",
      hooks_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/hooks",
      issue_events_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/issues/events{/number}",
      events_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/events",
      assignees_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/assignees{/user}",
      branches_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/branches{/branch}",
      tags_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/tags",
      blobs_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/git/blobs{/sha}",
      git_tags_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/git/tags{/sha}",
      git_refs_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/git/refs{/sha}",
      trees_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/git/trees{/sha}",
      statuses_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/statuses/{sha}",
      languages_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/languages",
      stargazers_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/stargazers",
      contributors_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/contributors",
      subscribers_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/subscribers",
      subscription_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/subscription",
      commits_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/commits{/sha}",
      git_commits_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/git/commits{/sha}",
      comments_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/comments{/number}",
      issue_comment_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/issues/comments{/number}",
      contents_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/contents/{+path}",
      compare_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/compare/{base}...{head}",
      merges_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/merges",
      archive_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/{archive_format}{/ref}",
      downloads_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/downloads",
      issues_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/issues{/number}",
      pulls_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/pulls{/number}",
      milestones_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/milestones{/number}",
      notifications_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/notifications{?since,all,participating}",
      labels_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/labels{/name}",
      releases_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/releases{/id}",
      deployments_url: "https://api.github.com/repos/PeterH3G/peterh3g.github.io/deployments",
      created_at: "2025-05-15T12:50:17Z",
      updated_at: "2025-11-08T19:13:54Z",
      pushed_at: "2025-11-08T19:38:06Z",
      git_url: "git://github.com/PeterH3G/peterh3g.github.io.git",
      ssh_url: "git@github.com:PeterH3G/peterh3g.github.io.git",
      clone_url: "https://github.com/PeterH3G/peterh3g.github.io.git",
      svn_url: "https://github.com/PeterH3G/peterh3g.github.io",
      homepage: "https://peterh3g.github.io/",
      size: 914,
      stargazers_count: 0,
      watchers_count: 0,
      language: null,
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: true,
      has_discussions: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: ["nuxt", "nuxt-ui", "tailwindcss", "typescript", "vuejs"],
      visibility: "public",
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: "main"
    }
  ];
  const content = [
    {
      name: ".gitignore",
      path: ".gitignore",
      sha: "dfcfd56f444f9ae40e1082c07fe254cc547136cf",
      size: 6002,
      url: "https://api.github.com/repos/PeterH3G/peterh3g/contents/.gitignore?ref=main",
      html_url: "https://github.com/PeterH3G/peterh3g/blob/main/.gitignore",
      git_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/dfcfd56f444f9ae40e1082c07fe254cc547136cf",
      download_url: "https://raw.githubusercontent.com/PeterH3G/peterh3g/main/.gitignore",
      type: "file",
      _links: {
        self: "https://api.github.com/repos/PeterH3G/peterh3g/contents/.gitignore?ref=main",
        git: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/dfcfd56f444f9ae40e1082c07fe254cc547136cf",
        html: "https://github.com/PeterH3G/peterh3g/blob/main/.gitignore"
      }
    },
    {
      name: ".nojekyll",
      path: ".nojekyll",
      sha: "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391",
      size: 0,
      url: "https://api.github.com/repos/PeterH3G/peterh3g/contents/.nojekyll?ref=main",
      html_url: "https://github.com/PeterH3G/peterh3g/blob/main/.nojekyll",
      git_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/e69de29bb2d1d6434b8b29ae775ad8c2e48c5391",
      download_url: "https://raw.githubusercontent.com/PeterH3G/peterh3g/main/.nojekyll",
      type: "file",
      _links: {
        self: "https://api.github.com/repos/PeterH3G/peterh3g/contents/.nojekyll?ref=main",
        git: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/e69de29bb2d1d6434b8b29ae775ad8c2e48c5391",
        html: "https://github.com/PeterH3G/peterh3g/blob/main/.nojekyll"
      }
    },
    {
      name: "LICENSE",
      path: "LICENSE",
      sha: "66169cb198e0d81029ee12dfeb1b62b5398c3b48",
      size: 1065,
      url: "https://api.github.com/repos/PeterH3G/peterh3g/contents/LICENSE?ref=main",
      html_url: "https://github.com/PeterH3G/peterh3g/blob/main/LICENSE",
      git_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/66169cb198e0d81029ee12dfeb1b62b5398c3b48",
      download_url: "https://raw.githubusercontent.com/PeterH3G/peterh3g/main/LICENSE",
      type: "file",
      _links: {
        self: "https://api.github.com/repos/PeterH3G/peterh3g/contents/LICENSE?ref=main",
        git: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/66169cb198e0d81029ee12dfeb1b62b5398c3b48",
        html: "https://github.com/PeterH3G/peterh3g/blob/main/LICENSE"
      }
    },
    {
      name: "README.md",
      path: "README.md",
      sha: "c5680e54f0ac0e87632b3b732299185dccae2ee9",
      size: 18,
      url: "https://api.github.com/repos/PeterH3G/peterh3g/contents/README.md?ref=main",
      html_url: "https://github.com/PeterH3G/peterh3g/blob/main/README.md",
      git_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/c5680e54f0ac0e87632b3b732299185dccae2ee9",
      download_url: "https://raw.githubusercontent.com/PeterH3G/peterh3g/main/README.md",
      type: "file",
      _links: {
        self: "https://api.github.com/repos/PeterH3G/peterh3g/contents/README.md?ref=main",
        git: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/c5680e54f0ac0e87632b3b732299185dccae2ee9",
        html: "https://github.com/PeterH3G/peterh3g/blob/main/README.md"
      }
    },
    {
      name: "README.svg",
      path: "README.svg",
      sha: "7af853cb14e7db8e0665121db536f5cf61daf9ed",
      size: 1438,
      url: "https://api.github.com/repos/PeterH3G/peterh3g/contents/README.svg?ref=main",
      html_url: "https://github.com/PeterH3G/peterh3g/blob/main/README.svg",
      git_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/7af853cb14e7db8e0665121db536f5cf61daf9ed",
      download_url: "https://raw.githubusercontent.com/PeterH3G/peterh3g/main/README.svg",
      type: "file",
      _links: {
        self: "https://api.github.com/repos/PeterH3G/peterh3g/contents/README.svg?ref=main",
        git: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/7af853cb14e7db8e0665121db536f5cf61daf9ed",
        html: "https://github.com/PeterH3G/peterh3g/blob/main/README.svg"
      }
    },
    {
      name: "README_OLD.md",
      path: "README_OLD.md",
      sha: "6696f74454cc389de74b107bc5d98313cc8d0b0e",
      size: 7607,
      url: "https://api.github.com/repos/PeterH3G/peterh3g/contents/README_OLD.md?ref=main",
      html_url: "https://github.com/PeterH3G/peterh3g/blob/main/README_OLD.md",
      git_url: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/6696f74454cc389de74b107bc5d98313cc8d0b0e",
      download_url: "https://raw.githubusercontent.com/PeterH3G/peterh3g/main/README_OLD.md",
      type: "file",
      _links: {
        self: "https://api.github.com/repos/PeterH3G/peterh3g/contents/README_OLD.md?ref=main",
        git: "https://api.github.com/repos/PeterH3G/peterh3g/git/blobs/6696f74454cc389de74b107bc5d98313cc8d0b0e",
        html: "https://github.com/PeterH3G/peterh3g/blob/main/README_OLD.md"
      }
    }
  ];
  return {
    peter3hg,
    repositories,
    content
  };
});

export { github as default };
//# sourceMappingURL=github.mjs.map
